# - Try to find Readline
# Once done this will define
#
#  READLINE_FOUND       - system has Readline
#  READLINE_INCLUDE_DIR - the Readline include directory
#  READLINE_LIBRARIES   - Link these to use Readline

include(FindTermcap)

set(READLINE_FOUND FALSE)

FIND_PATH(READLINE_INCLUDE_DIR readline/readline.h )

FIND_LIBRARY(READLINE_HISTORY_LIBRARY NAMES history )
FIND_LIBRARY(READLINE_READLINE_LIBRARY NAMES readline )

if(READLINE_HISTORY_LIBRARY AND READLINE_READLINE_LIBRARY AND READLINE_INCLUDE_DIR)
    set (READLINE_FOUND TRUE)
    set (READLINE_INCLUDE_DIR ${READLINE_INCLUDE_DIR})
    set (READLINE_LIBRARIES ${READLINE_HISTORY_LIBRARY} ${READLINE_READLINE_LIBRARY})
    if(TERMCAP_FOUND)
        set (READLINE_LIBRARIES ${READLINE_LIBRARIES} ${TERMCAP_LIBRARIES})
    endif(TERMCAP_FOUND)
    message(STATUS "Found GNU readline: ${READLINE_INCLUDE_DIR}, ${READLINE_LIBRARIES}")
endif(READLINE_HISTORY_LIBRARY AND READLINE_READLINE_LIBRARY AND READLINE_INCLUDE_DIR)

mark_as_advanced(READLINE_FOUND READLINE_INCLUDE_DIR READLINE_LIBRARIES READLINE_HISTORY_LIBRARY READLINE_READLINE_LIBRARY)
